apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pvc-deploy
  namespace: team-1-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pvc
  template:
    metadata:
      labels:
        app: test-pvc
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "sleep 3600"]
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: team1-pvc
